### ISSUE TITLE
fxp2ardour python error

### ISSUE THREAD

**Issue by pqks** [SpotlightKid/ardour2fxp#1]
Hi. I have a error message when I try convert fxp file to xml .

On terminal, write:
`$ fxp2ardour -o my-xml-presets ~/audio/plugins_presets/Obxd-new_strings.fxp`

Terminal out:
`Traceback (most recent call last):
  File "/home/audiopc/.local/bin/fxp2ardour", line 11, in <module>
    sys.exit(main())
  File "/home/audiopc/.local/lib/python2.7/site-packages/fxp2ardour.py", line 116, in main
    sha1.update(bytes(preset.label, 'latin1'))
TypeError: str() takes at most 1 argument (2 given)`

P.D.: On the README file and the info on github repository the command for convert fxp files to xml is wrong type: `fxp2ardour2`

**Comment by SpotlightKid** [comment]
This software requires Python 3, Python 2 is not supported. See the README and `setup.py`.

The typo in the README is fixed in 53750bcd847ea1331631903a139c96e7e53cba69. Thanks for pointing it out.

**Comment by mvondr** [comment]
Hi, I have an error message, when I try to merge or append preset for Ardour 6:
`$ fxp2ardour -a -o "C:\Users\mvond\AppData\Local\Ardour6\presets" "C:\Users\mvond\vst\SuperWave\P8\Patches\P8 - Factory Patches\Strings\P8 - Violin 2003.fxp"`

Terminal output:
`Traceback (most recent call last):
  File "C:\Users\mvond\AppData\Local\Programs\Python\Python37-32\Scripts\fxp2ardour-script.py", line 11, in <module>
    load_entry_point('ardour2fxp==0.1.0b1', 'console_scripts', 'fxp2ardour')()
  File "c:\users\mvond\appdata\local\programs\python\python37-32\lib\site-packages\fxp2ardour.py", line 130, in main
    for node in root.childNodes:
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'childNodes'
`

The error message is the same for input parameter -m.

**Comment by SpotlightKid** [comment]
@MVO2015: Fixed in 0a5f186. Please open a new ticket when reporting new problems next time. Thanks!
