### ISSUE TITLE
Parsing argument problem on Windows 10

### ISSUE THREAD

**Issue by mvondr** [SpotlightKid/ardour2fxp#2]
Hi, I found issue probably concerning to argument parser.
This works:
`$ cd "/c/Users/mvond/vst/P8/Patches/P8 - Factory Patches/Pads"`
`$ ~/projects/ardour2fxp/fxp2ardour.py -m -o "C:/Users/mvond/AppData/Local/Ardour6/presets"  *.fxp`

But this does not:
`$ cd "/c/Users/mvond/projects/ardour2fxp"`
`$ fxp2ardour -m -o 'C:\Users\mvond\AppData\Local\Ardour6\presets' 'C:\Users\mvond\vst\P8\Patches\P8 - Factory Patches\Pads\*.fxp'
Error reading FXP preset file 'C:\Users\mvond\vst\P8\Patches\P8 - Factory Patches\Pads\*.fxp': [Errno 22] Invalid argument: 'C:\\Users\\mvond\\vst\\P8\\Patches\\P8 - Factory Patches\\Pads\\*.fxp'`

I suppose that spaces in the path make problems. I ran it from Git Bash on Windows 10, but in cmd is the same. I tried quotes, double quotes, escaping spaces etc.

**Comment by SpotlightKid** [comment]
You can't put shell globs like `*` in quotes. Put the closing single quote after the last backslash and before the `*.fxp`, no space in between.

**Comment by mvondr** [comment]
It does the same:
`$ fxp2ardour -m -o 'C:\Users\mvond\AppData\Local\Ardour6\presets' 'C:\Users\mvond\vst\P8\Patches\P8 - Factory Patches\Pads\'*.fxp`
`Error reading FXP preset file 'C:\Users\mvond\vst\P8\Patches\P8 - Factory Patches\Pads\*.fxp': [Errno 22] Invalid argument: 'C:\\Users\\mvond\\vst\\P8\\Patches\\P8 - Factory Patches\\Pads\\*.fxp'
`

And the other error I get if there is specific filename:
`$ fxp2ardour -m -o 'C:\Users\mvond\AppData\Local\Ardour6\presets' 'C:\Users\mvond\vst\P8\Patches\P8 - Factory Patches\Strings\P8 - Violin 2003.fxp'`
`Traceback (most recent call last):
  File "C:\Users\mvond\AppData\Local\Programs\Python\Python37-32\Scripts\fxp2ardour-script.py", line 11, in <module>
    load_entry_point('ardour2fxp==0.1.0b1', 'console_scripts', 'fxp2ardour')()
  File "c:\users\mvond\appdata\local\programs\python\python37-32\lib\site-packages\fxp2ardour.py", line 130, in main
    for node in root.childNodes:
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'childNodes'
`

**Comment by SpotlightKid** [comment]
I released a new version a few hours ago. please update and test again.

**Comment by SpotlightKid** [comment]
Also, are you using the windows command prompt? that doesn't actually support globs like unix shells do.

**Comment by mvondr** [comment]
I hope I am using the last version (there is no --version argument to find out it). But I did `git pull` and `pip install ardour2fxp`
(and `fxp2ardour` not sure if necessary none, one or both).
`$ git log`
```
commit 9063c321f0b0f08bcdea0a8e88b47f14dd72f858 (HEAD -> master, origin/master, origin/HEAD)
Author: Christopher Arndt <chris@chrisarndt.de>
Date:   Fri Jan 15 03:25:01 2021 +0100

    Use VST2 (instead only VST) in readme

    Signed-off-by: Christopher Arndt <chris@chrisarndt.de>`
I still think there is a problem with spaces in arguments and its parsing.
```

In **cmd** with double quotes:
`>fxp2ardour -m -o C:\Users\mvond\AppData\Local\Ardour6\presets "C:\Users\mvond\vst\P8\Patches\P8 - Factory Patches\Strings\P8 - Violin 2003.fxp"`

```
Traceback (most recent call last):
  File "C:\Users\mvond\AppData\Local\Programs\Python\Python37-32\Scripts\fxp2ardour-script.py", line 11, in <module>
    load_entry_point('ardour2fxp==0.1.0b1', 'console_scripts', 'fxp2ardour')()
  File "c:\users\mvond\appdata\local\programs\python\python37-32\lib\site-packages\fxp2ardour.py", line 130, in main
    for node in root.childNodes:
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'childNodes'
```

In **cmd** with single quotes (look at the end of the argument in the output):
`>fxp2ardour -m -o C:\Users\mvond\AppData\Local\Ardour6\presets 'C:\Users\mvond\vst\P8\Patches\P8 - Factory Patches\Strings\P8 - Violin 2003.fxp'`

```
Error reading FXP preset file ''C:\Users\mvond\vst\P8\Patches\P8': [Errno 22] Invalid argument: "'C:\\Users\\mvond\\vst\\P8\\Patches\\P8"
```

Oh, it looks that single quote is part of string, so that it is not right use them. In that case it is not issue of quotes.

**Comment by SpotlightKid** [comment]
When you use `pip install ardour2fxp` you are always installing from PyPI, not from your local git checkout (which seems to be up to date). But the `xml.etree.ElementTree.Element` error indicates you are still running an old version, which had this error on line 130. The up -to-date code, which is in the latest release has this fixed. If you want to re-install fromPyPI, you need to use `pip install -U ardour2fxp` (note the `-U` option).

**Comment by SpotlightKid** [comment]
Regarding the command line: I'm not familiar in detail with the quirks of the Windows command interpreter, but I would suggest using double quotes where possible. If you need to use shell globs, use a different comman line interpreter, e.g. try  WSL or install Bash for Windows. Maybe even Power Shell, but I have no idea whether that works.

All I know is that the scripts will use whatever filenames you pass to them on the command line as single, separate arguments  *unchanged*. So it's a matter of getting the command line arguments right, not of parsing them.

**Comment by mvondr** [comment]
Christopher, thank you for your work and patience.
I think, it is almost clear now. You can close this issue.

*Summary*:
All is working well in Git Bash - important is to use single quotes for path with spaces and use slashes, e.g.:
`$ fxp2ardour -m -o C:/Users/mvond/AppData/Local/Ardour6/presets 'C:/Users/mvond/vst/P8/Patches/P8 - Factory Patches/Strings/'*
`
In cmd and Power Shell: unfortunately there is a problem with wildcard - only one file can be added/merged. Use double quotes for path with spaces and use slashes or backslashes, e.g.:
`>fxp2ardour -m -o C:\Users\mvond\AppData\Local\Ardour6\presets "C:\Users\mvond\vst\P8\Patches\P8 - Factory Patches\Strings\P8 - Violin 2003.fxp"`

**Comment by SpotlightKid** [comment]
Glad to hear you got it working somehow.

I'll try to test this on Windows myself the next time I boot up my Windows PC.
